### ISSUE TITLE
Policy "CMP0048" is not known to this version of CMake

### ISSUE THREAD

**Issue by HYChou0515** [zeyiwen/thundersvm#32]
I follow [Working without GPUs](http://thundersvm.readthedocs.io/en/latest/get-started.html#working-without-gpus) 
`# in thundersvm root directory`
`git submodule init eigen && git submodule update`
`mkdir build && cd build && cmake -DUSE_CUDA=OFF -DUSE_EIGEN=ON .. && make -j`

I got this
```
CMake Error at CMakeLists.txt:3 (cmake_policy):
  Policy "CMP0048" is not known to this version of CMake.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_VERSION_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_VERSION_COMPILER
...
```

So I had a quick [google](https://cmake.org/cmake/help/v3.0/policy/CMP0048.html) and found that

> The project() command manages VERSION variables.
> 
> CMake version 3.0 introduced the VERSION option of the project() command to specify a project version as well as the name. ...

So maybe it's not working under cmake version 2.8 which is my case.

my environment
```
cmake version 2.8.12.2
gcc version 4.8.4
```

**Comment by shijiashuai** [comment]
Thanks for the issue. I have updated `CMakeLists.txt`. And it should work normally with CMake 2.8.12.

**Comment by HYChou0515** [comment]
Thanks, it works like a charm.
