### ISSUE TITLE
Sklearn Interface

### ISSUE THREAD

**Issue by divamgupta** [zeyiwen/thundersvm#33]
Are there any plans for making an sklearn interface for thunder svm?

**Comment by zeyiwen** [comment]
Yes. We aim to provide scikit-learn interfaces around mid 2018 according to our schedule. If our user community could help on developing scikit-learn interfaces, that would be wonderful. You are more than welcome to contribute to improving ThunderSVM.

**Comment by zeyiwen** [comment]
@divamgupta The latest version of ThunderSVM supports scikit-learn now. Please clone the repository and have a try.
