### ISSUE TITLE
Compilation fails with gcc 5.x

### ISSUE THREAD

**Issue by gkoundry** [zeyiwen/thundersvm#34]
Compilation with gcc 5.4.0 gives the following:

```
usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
```

Adding the following to `CMakeLists.txt` fixes the problem:

`SET ( CMAKE_CXX_FLAGS "-D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES" CACHE STRING "compile flags" FORCE)`

**Comment by zeyiwen** [comment]
Thank you for the information! We'll test the suggested improvement and update the `CMakeLists.txt` file.

**Comment by shijiashuai** [comment]
Thank you.

According to the similar issues (tensorflow/tensorflow#1066 and NVIDIA/nccl#29), the problem comes from CUDA 7.5 with FC23.

Adding the flags does solve the problem, but it doesn't seem to be a best practice here. I am considering adding the solution to documents or modifying the CUDA requirements. You could upgrade CUDA toolkit to avoid the problem.

**Comment by cyou6** [comment]
> Compilation with gcc 5.4.0 gives the following:
> 
> ```
> usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
> 
> /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
> 
> /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
> 
> /usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined
> ```
> Adding the following to `CMakeLists.txt` fixes the problem:
> 
> `SET ( CMAKE_CXX_FLAGS "-D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES" CACHE STRING "compile flags" FORCE)`

Hi, I am new using Ubuntu. Where can I find the right CMakeLists.txt? I am using a catkin workspace with many CMakeLists.txt there
