### ISSUE TITLE
Predict method doesn't create file if it doesn't exist already

### ISSUE THREAD

**Issue by jputila** [zeyiwen/thundersvm#36]
OS: Ubuntu 16.04, gcc 5.4.0

Changing the line in `thundersvm-predict.cpp` as follows seems to fix it.

`file.open(parser.svmpredict_output_file);`

...to...

`file.open(parser.svmpredict_output_file, fstream::out);`

**Comment by zeyiwen** [comment]
Hah, thanks for the feedback! We'll take a look and improve it.

**Comment by bingshenghe** [comment]
@jputila you are so considerate :)
