### ISSUE TITLE
Out of memory error in training and predicting while using rcv1 dataset

### ISSUE THREAD

**Issue by ELFairyhyuk** [zeyiwen/thundersvm#38]
$./bin/thundersvm-train -c 32 -g 1 dataset/rcv1
$./bin/thundersvm-predict dataset/rcv1.t  rcv1.model rcv1.predict
When use dataset rcv1 from libsvm website, "out of memory" error appeared in training and predicting. Details are as follows:

<img width="736" alt="2018-01-04 10 22 08" src="https://user-images.githubusercontent.com/17524724/34548057-2cfdcc0a-f0c5-11e7-8ad6-42ba325d5004.png">

**Comment by zeyiwen** [comment]
We can't reproduce the issue in the current version. It seems to be the problem of a earlier version of ThunderSVM. Closed after confirmation with @ELFairyhyuk
