### ISSUE TITLE
Kernel dies when using weighted C-SVC

### ISSUE THREAD

**Issue by msalvaris** [zeyiwen/thundersvm#43]
I am trying to train an SVM model from python with the following parameters -s 0 -t 0 -c 1 -b 1 -u 0 -w1 10 -w-1 1 and my Jupyter kernel dies. If I train with -s 0 -t 0 -c 1 -b 1 -u 0 it trains fine. I am importing the functions from svm.py and running them inside a jupyter notebook on a Python 3.5.2 conda environment on a Ubuntu Linux VM.

**Comment by GODqinbin** [comment]
Thanks for your feedback. I found the bug on command line parser and I have already fixed it. You can update code and try again.

**Comment by msalvaris** [comment]
Yep, looks good. Unbelievably fast response
