### ISSUE TITLE
Using weighted C-SVC

### ISSUE THREAD

**Issue by msalvaris** [zeyiwen/thundersvm#44]
I am trying to train an SVM model from python with the following parameters -s 0 -t 0 -c 1 -b 1 -u 0 -w1 100

I have tried different values for -w1 but the SVM fails to learn anything I am guessing because the classes are heavily imbalance and the weighting isn't being applied?

My train_y is a list that contains 1 and -1. I am importing the functions from svm.py and running them inside a jupyter notebook on a Python 3.5.2 conda environment on a Ubuntu Linux VM.

**Comment by GODqinbin** [comment]
I use dataset a9a to test and the weighting is applied successfully. Would you please attach the full log? Alternatively, you can use publicly available datasets to produce the issue again, and then we can debug the code.
