### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by RKolhatkar** [zeyiwen/thundersvm#47]
Getting this while executing the sample set. Thundersvm was built successfully.
Cuda version: cuda-9.1.85.2-1
Manjaro Linux, GeForce 840M

**Comment by zeyiwen** [comment]
It seems you haven't installed CUDA driver properly. Check out [this link](https://stackoverflow.com/questions/41409842/ubuntu-16-04-cuda-8-cuda-driver-version-is-insufficient-for-cuda-runtime-vers) for some information. You may need to manually install the driver while you are installing CUDA.

**Comment by RKolhatkar** [comment]
I downloaded the nvidia390 package from the website and now the error == CudaSuccess is showing Unknown Error.

I downloaded the CUDA 9.1 package from the nvidia website and installed it using pacman.
