### ISSUE TITLE
Taking too long to train a relatively small model

### ISSUE THREAD

**Issue by julianofoleiss** [zeyiwen/thundersvm#48]
I'm trying to train a 156d model with 36k examples. Sklearn does it in 180s. However, thundersvm is already running it for 90 hours.

Here is my system:

GTX 780, 4GB
log: [logfile](https://pastebin.com/VjHa0etZ)

nvcc --version
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

gcc --version
gcc (Ubuntu 4.9.3-13ubuntu2) 4.9.3

I'm not sure what to try next.

Thanks!

**Comment by zeyiwen** [comment]
The log looks a bit strange, and shows ThunderSVM loads ```../dataset/gtzan_f1_train_libsvm.txt``` twice. ThunderSVM got stuck after the second loading... 

I noticed you are not using a public data set, and hence it is difficult for us to reproduce the issue. Would you share your data set with us? My email address is wenzy@comp.nus.edu.sg.

**Comment by julianofoleiss** [comment]
I'm sorry! The output I copied was messed up. I ran again, and the problem persists. The log:
[gtzan_f1_train_thunder.txt](https://github.com/zeyiwen/thundersvm/files/1869455/gtzan_f1_train_thunder.txt)

Here is the train file: [gtzan_f1_train.tar.gz](https://drive.google.com/open?id=1e_lrUpKUOpvMM3OwK3CxF0Jno6wJG7t1)

Thank you very much for looking into this!

**Comment by julianofoleiss** [comment]
As a follow up, the same thing happened with a newer GPU (1070GTX, 12GB of RAM) and Cuda 9.0.

**Comment by shijiashuai** [comment]
We have reproduced the problem and are fixing it. For now, I have some practical solutions that may help you.

1. scale your dataset
Scaling makes convergence faster and support vectors less. Note that you should scale your testing set correspondingly. [here](https://drive.google.com/file/d/1e_lrUpKUOpvMM3OwK3CxF0Jno6wJG7t1/view?usp=sharing) is the scaled dataset I tested. (scaled to [-1, 1])
2. try gamma = 0.059 (or 0.0599) instead of 0.06 to jump out of stuck.

**Comment by julianofoleiss** [comment]
Thank you very much!

I actually knew that scaling speeds it up and I thought I had done it!

Thanks again!

**Comment by julianofoleiss** [comment]
Awesome! I'll test it as well! If I find any other problems, I'll report them!

Thanks!

**Comment by zeyiwen** [comment]
We have merged the code to master now, and would like to close this issue. Thanks.
