### ISSUE TITLE
Crash on Windows + Matlab + Visual Studio

### ISSUE THREAD

**Issue by zhou-heng** [zeyiwen/thundersvm#51]
Environment:
- Windows 10
- Matlab R2017a
- Visual Studio 2015
- nVidia GeForce GTX 1050 Ti with newest driver installed
- CUDA 9.1

I compiled thundersvm on Windows using steps described in the online doc, i.e., cmake and then compile in VS2015. The output directory of executibles is "......\thundersvm-master\build\bin\Release" and the shared library is called "thundersvm.dll" on Windows. I am using the MNIST data set which is uncompressed to E:\mnist.scale. The output executible "thundersvm-train.exe" works fine on command line (accuracy is about 94%): 
`thundersvm-train E:\mnist.scale E:\mnist.model`
so I think the compiling step should be correct. But it crashes in Matlab. The Matlab testing code is:
```
n = ["-c", "10", "-g", "0.125", "E:\mnist.scale", "E:\mnist.model"];
m = cellstr(n);
svm_train_matlab(m)
```
Since the directory and filenames are different on Windows, I changed svm_train_matlab.m to:
```
function svm_train_matlab(a)
    if not(libisloaded('thundersvm'))
        loadlibrary('......\thundersvm-master\build\bin\Release\thundersvm.dll', ...
            '......\thundersvm-master\include\thundersvm\svm_matlab_interface.h')
    end
	str = {'thundersvm-train'};
	str2 = [str a]
	calllib('thundersvm', 'thundersvm_train_matlab', length(str2), str2)
end

```
In all above codes, ...... in the path is the leading directory before thundersvm's root which is omitted. When I debugged my Matlab code, everything works fine until the last line calllib(...). Once I step over or into it, Matlab crashes, saying "MATLAB R2017a has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available." Since I can run the training code correctly on Windows command line, I guess the problem might be parameter values or parameter passing for calllib. I am not very familiar with this part of Matlab code, so could you please help me with this crash problem? Or can you tell me how to put a printf-like code in the interface code so that I can check the parameters passed myself (I know it's in thundersvm_train_matlab function of src\svm_matlab_interface.cpp)? Please let me know if you need more info. Thank you for your help.

**Comment by GODqinbin** [comment]
Thanks for your feedback. I think the problem may be the path of your dataset. The Matlab interface doesn't support absolute path yet. The default dataset path of Matlab interface is the "dataset" dir. You can change "E:\mnist.scale" and "E:\mnist.model" to the relative path to "dataset" dir. Or put your dataset in "dataset" dir and use "mnist.scale". If problem still exists, please let us know. We will fix the path bug later.

**Comment by zhou-heng** [comment]
Thank you for the prompt reply. I agree with you. I would like to create a "dataset" dir, copy "E:\mnist.scale" into it, and change the testing code to
`n = ["-c", "10", "-g", "0.125", "mnist.scale", "mnist.model"];`

But I tried several directories and got the same crash. I checked the svm_matlab_interface.cpp and guess that the "dataset" dir is defined in DATASET_DIR, right? And then I found that this macro is defined in cmake and I am at my wit's end. So, assuming my testing matlab code is contained in dir ......\Test, I tried to create "dataset" dir in this dir and copy E:\mnist.scale into it. Matlab still crashes. Then I realized that DATASET_DIR is used in C++ code which forms the "thundersvm.dll", so the "dataset" dir should be relative to the dir of this dll file. So I created "dataset" dir in ......\thundersvm-master\build\bin\Release\ and copy E:\mnist.scale into it. Matlab still crashes. I also tried to create "dataset" dir in the Matlab dir under the of thundersvm's root, but received the same crash. So, could you please tell me where I should create the "dataset" dir in? Besides, is it possible that I need to add "\\" or ".\\" or something like in front of "mnist.scale" and "mnist.model"? Thanks again for your help.

**Comment by GODqinbin** [comment]
There should be a "dataset" dir in your thundersvm-master. You needn't to create a new one. Just put the mnist.scale in your "thundersvm-master\dataset".

**Comment by zhou-heng** [comment]
Yes, it is working now! Thank you very much for your help.

**Comment by GODqinbin** [comment]
You're welcome. We'll fix the bug later. The scikit interface in "python" dir is more user-friendly.
