### ISSUE TITLE
Cross Validation issue

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [zeyiwen/thundersvm#55]
Hi,

I am trying to do cross-validation in matlab in order to find the right parameters. It finishes doing CV successfully, but I don't get any score representing how good the parameters are.

My command is as follows,
svm_train_matlab({'-v', '5', '-c', num2str(2^log2c), '-g', num2str(2^log2g), 'feat.train', 'cv_new'})

And while actual training, is there a way to store the model in matlab structure format like we do with libsvm.

Thanks for this framework. And thanks for your time.

Regards,
Aditya

**Comment by GODqinbin** [comment]
Thanks for your feedback. We have updated the codes. You can update it and try again. After you run the cross-validation, you can find a log file in your working directory. You can find the Accuracy score in the log file.

We don't store the model in cross-validation. We can save the model in file format if you don't add '-v' parameter. We may improve the Matlab interface in the future to store the model in matlab structure.

**Comment by aditya-jonnalagadda** [comment]
Thank you. Now, I am getting the accuracy.

Regards,
Aditya
