### ISSUE TITLE
How to set gpu memory limit and save trained model with scikit-learn wrapper interface?

### ISSUE THREAD

**Issue by pranerd** [zeyiwen/thundersvm#57]
I used with scikit-learn wrapper interface,  come up with some  problem.
1. how to set the memory limit like cmd interface -m xxx?
2. how to save trained model? I try to use with pickle.dump, but it didn't work.

**Comment by GODqinbin** [comment]
Thanks for your feedback. Now we add the memory limit parameter, save_to_file function and load_from_file function. You can refer to the docs in [https://github.com/zeyiwen/thundersvm/tree/master/python]. You can update the codes and have a try.

**Comment by zeyiwen** [comment]
I believe this issue is solved, and would like to close it. Thanks!
