### ISSUE TITLE
Query regarding linear kernel

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [zeyiwen/thundersvm#61]
Hi,

I am using a linear kernel with '-t 0' option. In order to compute the weight vector, I am reading the model file line by line and adding coefficient*support_vector to my global weight vector. Once I go through all the support vectors, I will have my final weight vector. This was the equivalent of the approach described in libsvm FAQ.

As I am reading my model file line by line, it is taking some extra time for this computation. Is there a simpler way of getting the weight vector for thundersvm.

Thanks for your time.

Regards,
Aditya

**Comment by zeyiwen** [comment]
ThunderSVM doesn't have that functionality yet, but we will consider implementing it in the future version. Thanks for the feedback!

**Comment by aditya-jonnalagadda** [comment]
Thank you.
