### ISSUE TITLE
Build error Windows Visual studio 2017

### ISSUE THREAD

**Issue by ericqu** [zeyiwen/thundersvm#62]
windows 10, visual studio 2017, cuda 9.1

`git clone https://github.com/zeyiwen/thundersvm.git
cd thundersvm
mkdir build
cd build
cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "Visual Studio 15 2017 Win64"`

`-- The C compiler identification is MSVC 19.13.26131.1
-- The CXX compiler identification is MSVC 19.13.26131.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Compile with CUDA
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Eric/source/repos/thundersvm/build`

then I open the solution with Visual studio, select the "Release" and build it, the following output it generated:

`1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because C:/Users/Me/source/repos/thundersvm/build/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: thundersvm, Configuration: Release x64 ------
2>Building NVCC (Device) object src/thundersvm/CMakeFiles/thundersvm.dir/kernel/Release/thundersvm_generated_kernelmatrix_kernel.cu.obj
2>kernelmatrix_kernel.cu
2>CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(506): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(507): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(508): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(540): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(1045): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(1560): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(2375): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits(2375): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xutility(543): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtr1common(58): error : class "std::enable_if<<error-constant>, int>" has no member "type"
2>          detected during instantiation of type "std::enable_if_t<<error-constant>, int>"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xutility(543): here
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xmemory0(363): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xmemory0(981): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xmemory0(1302): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xstring(1891): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtr1common(58): error : class "std::enable_if<<error-constant>, void>" has no member "type"
2>          detected during instantiation of type "std::enable_if_t<<error-constant>, void>"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xstring(1891): here
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xutility(298): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\vector(474): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(88): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(89): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(90): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(109): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(110): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(111): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(163): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(182): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(184): error : invalid redeclaration of member function template "std::_Tuple_val<_Ty>::_Tuple_val(const _Alloc &, std::allocator_arg_t, _Other &&...)"
2>(164): here
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(864): error : no instance of overloaded function "std::tuple<_This, _Rest...>::tuple" matches the specified type
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\tuple(876): error : no instance of overloaded function "std::tuple<_This, _Rest...>::tuple" matches the specified type
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(589): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xtree(1345): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\functional(401): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\memory(1540): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\memory(1547): error : expression must have a constant value
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\memory(2496): error : constant value is not known
2>
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\memory(2596): error : expression must have a constant value
2>
2>c:\users\me\source\repos\thundersvm\include\thundersvm\util/log.h(1361): warning : exception specification for virtual function "el::base::utils::AbstractRegistry<T_Ptr, Container>::~AbstractRegistry [with T_Ptr=T_Ptr, Container=std::map<T_Key, T_Ptr *, std::less<T_Key>, std::allocator<std::pair<const T_Key, T_Ptr *>>>]" is incompatible with that of overridden function "el::base::threading::ThreadSafe::~ThreadSafe"
2>
2>c:\users\me\source\repos\thundersvm\include\thundersvm\util/log.h(1361): warning : exception specification for virtual function "el::base::utils::AbstractRegistry<T_Ptr, Container>::~AbstractRegistry [with T_Ptr=T_Ptr, Container=std::vector<T_Ptr *, std::allocator<T_Ptr *>>]" is incompatible with that of overridden function "el::base::threading::ThreadSafe::~ThreadSafe"
2>
2>0x00007FF7F5CF40C5 (0x0000000000000000 0x00000274703B2908 0x0000027468432428 0x0000000000000000)
2>0x00007FF7F5CF0E48 (0x0000000000000000 0x0000027400000000 0x0000000000000000 0x0000000000000000)
2>0x00007FF7F5CF1BA2 (0x00000274703D17E0 0x0000000000000000 0x0000000000000000 0x0000000000000000)
2>0x00007FF7F5D25B45 (0x00000274703AFC07 0x0000000000000001 0x0000027400000001 0x0000000000000001)
2>0x00007FF7F5D20083 (0x0000027400000001 0x0000009C3B9FC608 0x0000009C3B9FCCB0 0x0000000000000001)
2>0x00007FF7F5BA40A7 (0x0000009C00000000 0x0000000000000000 0x0000009C3B9FC6F0 0x00000274703B2878)
2>0x00007FF7F5BA9461 (0x0000000000000001 0x000000003892A7CC 0x0000000000000000 0x00007FF7F5D16B30)
2>0x00007FF7F5BA9160 (0x0000000000000800 0x0000000000000001 0x0000027400000000 0x0000000000000000)
2>0x00007FF7F5C0B8AD (0x000002747038F668 0x00000274703B27A0 0x000002747037C6D0 0x000002746624E5F8)
2>0x00007FF7F5C0C869 (0x000002746624E5F8 0x0000009C3B9FD5C0 0x000002747037C6D0 0x00007FF7F5C04D0D)
2>0x00007FF7F5C0B6D8 (0x000002746624E5F8 0x00000274703B2830 0x0000000000000000 0x00000274702F5780)
2>0x00007FF7F5D315CD (0x0000027470367C38 0x0000009C3B9FD230 0x000002747038F0C8 0x00000274681A5340)
2>0x00007FF7F5D18F40 (0x00000274681A5D78 0x000002747038F0C8 0x00000274681A5340 0x00007FF700000000)
2>0x00007FF7F5D189E2 (0x0000000000000000 0x0000009C3B9FD331 0x0000009C3B9FD5C0 0x0000000000000000)
2>0x00007FF7F5D1996D (0x0000000000000000 0x00000274703B27A0 0x000002747037C6D0 0x000002747037E220)
2>0x00007FF7F5D199E6 (0x0000000000000000 0x00000274703B27A0 0x000002747037C6D0 0x000002747037E220)
2>0x00007FF7F5D313E9 (0x0000000000000000 0x0000009C3B9FD700 0x00000274703B27A0 0x0000000000000001)
2>0x00007FF7F5D125A8 (0x00000274703B27A0 0x000002747037E1F0 0x0000009C00000000 0x000002747037E1F0)
2>0x00007FF7F5D36E1A (0x0000009C3B9FD7A8 0x0000000000000000 0x0000027470390228 0x0000000000000000)
2>0x00007FF7F5D36CD8 (0x000002747037E1F0 0x000002747037E268 0x0000000000000000 0x0000027470367EE0)
2>0x00007FF7F5CD1BA6 (0x0000000000000000 0x0000027468E37A68 0x00000274700AB910 0x0000000000000000)
2>0x00007FF7F5CCF11D (0x000002747037E1F0 0x000002747037C320 0x0000000000000000 0x000002747037E1F0)
2>0x00007FF7F5CDED0F (0x0000000000000000 0x00007FF700000000 0x0000000000000000 0x00000274700AB910)
2>0x00007FF7F5CDB62E (0x000002747037C320 0x0000009C00000000 0x0000000000000000 0x0000000000000001)
2>0x00007FF7F5BB31AF (0x000002747037C320 0x0000009C3B9FE050 0x0000027470367EE0 0x0000000000000000)
2>0x00007FF7F5BAF41E (0x0000027470367EE0 0x0000009C3B9FDEF0 0x0000000000000000 0x0000009C3B9FE050)
2>0x00007FF7F5B69289 (0x0000003F0007A5B7 0x0000000000124E44 0x00000274703C0A98 0x00000274703C0A50)
2>0x00007FF7F5B63938 (0x0000027470368AD8 0x0000000000000001 0x0000027470368A09 0x0000027400000000)
2>0x00007FF7F5BFCFE8 (0x0000027470368AD8 0x00000274702C7A00 0x0000027467BC865B 0x00000274702C7A00)
2>0x00007FF7F5B3781B (0x00000274661DDA08 0x0000027400000000 0x0000000000000000 0x0000000000000000)
2>0x00007FF7F5B3CA91 (0x0000009C3B9FEA10 0x0000009C3B9FE4F0 0x0000027470368068 0x00000274703741F8)
2>0x00007FF7F5B3CC16 (0x0000009C3B9FE4F0 0x0000009C3B9FEA10 0x0000000000000000 0x0000027470368068)
2>0x00007FF7F5B82DFE (0x000000000000000A 0x0000000000000000 0x0000000000000000 0x00007FF7F5D57E90)
2>0x00007FF7F5B857B7 (0x0000000008A008B3 0x0000000000000000 0x0000009C3B9FE940 0x0000009C00000000)
2>0x00007FF7F5B7BF52 (0x0000009C3B9FEB00 0x000015318DC1A4E1 0x0000000000000000 0x0000009C3B9FEB40)
2>0x00007FF7F5B73FE0 (0x0000000E0007A0F8 0x0000009C3B9FEC89 0x0000027470077E78 0x0000009C3B9FEC89)
2>0x00007FF7F5B78B51 (0x0000009C3B9FED80 0x0000027400000000 0x0000009C3B9FEF40 0x0000009C3B9FED60)
2>0x00007FF7F5B6CC8B (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000009C3B9FEE50)
2>0x00007FF7F5B7BE9C (0x00000274662527C0 0x0000027400000000 0x0000000000000000 0x0000000000000006)
2>0x00007FF7F5B7D65A (0x0000000000000000 0x0000027400000000 0x0000000000000000 0x0000000000000000)
2>0x00007FF7F5D45C84 (0x000002746617C750 0x0000027466190960 0x0000000000000000 0x0000000000000000)
2>0x00007FF7F5B0ECA1 (0x0000000000000000 0x000002746617C750 0x0000000000000000 0x000000000000000F)
2>CUSTOMBUILD : nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
2>kernelmatrix_kernel.cu
2>CUSTOMBUILD : nvcc error : 'cicc' died with status 0xC0000005 (ACCESS_VIOLATION)
2>0x00007FF7F5B0EE09 (0xCMake Error at thundersvm_generated_kernelmatrix_kernel.cu.obj.Release.cmake:279 (message):
2>  Error generating file
2>  C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/Release/thundersvm_generated_kernelmatrix_kernel.cu.obj
2>
2>
2>Done building project "thundersvm.vcxproj" -- FAILED.
3>------ Build started: Project: thundersvm-predict, Configuration: Release x64 ------
4>------ Build started: Project: thundersvm-train, Configuration: Release x64 ------
3>Building Custom Rule C:/Users/Me/source/repos/thundersvm/src/thundersvm/CMakeLists.txt
3>CMake is re-running because C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/generate.stamp is out-of-date.
3>  the file 'C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.obj.depend'
3>  is newer than 'C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/generate.stamp.depend'
3>  result='-1'
3>Compile with CUDA
3>-- Configuring done
4>Building Custom Rule C:/Users/Me/source/repos/thundersvm/src/thundersvm/CMakeLists.txt
4>CMake is re-running because C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/generate.stamp is out-of-date.
4>  the file 'C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/thundersvm.dir/kernel/thundersvm_generated_kernelmatrix_kernel.cu.obj.depend'
4>  is newer than 'C:/Users/Me/source/repos/thundersvm/build/src/thundersvm/CMakeFiles/generate.stamp.depend'
4>  result='-1'
3>-- Generating done
4>Compile with CUDA
3>-- Build files have been written to: C:/Users/Me/source/repos/thundersvm/build
4>-- Configuring done
3>thundersvm-predict.cpp
4>-- Generating done
4>-- Build files have been written to: C:/Users/Me/source/repos/thundersvm/build
4>thundersvm-train.cpp
3>LINK : fatal error LNK1181: cannot open input file '..\..\lib\Release\thundersvm.lib'
3>Done building project "thundersvm-predict.vcxproj" -- FAILED.
4>LINK : fatal error LNK1181: cannot open input file '..\..\lib\Release\thundersvm.lib'
4>Done building project "thundersvm-train.vcxproj" -- FAILED.
5>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 3 failed, 0 up-to-date, 1 skipped ==========`

I tried to force the language setting to /std:c++14 in visual studio to no effect. I guess it needs to be changed somewhere else.

**Comment by GODqinbin** [comment]
There are compatibility problems with CUDA 9.1 and Visual C++ 2017 Compiler. You can see [https://github.com/fireice-uk/xmr-stak/issues/91](url) for more information. We provided some solutions on the issue #45 [https://github.com/zeyiwen/thundersvm/issues/45](url). I suggest that you install Visual Studio 2015 v140 toolset and build with `cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE -G "Visual Studio 15 2017 Win64" -Tv140`. If the problem still exists, please let us know. Thanks.

**Comment by ericqu** [comment]
thanks for the feedback, sorry I missed the others entries. I think I will wait until it the incompatibilities are fixed.
