### ISSUE TITLE
Couple of errors while training

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [zeyiwen/thundersvm#63]
Hi,

I am seeing a crash sometimes while using thundersvm with matlab, the stack trace is as follows.

Stack Trace (from fault):
[  0] 0x00007f500d700428                    /lib/x86_64-linux-gnu/libc.so.6+00218152 gsignal+00000056
[  1] 0x00007f500d70202a                    /lib/x86_64-linux-gnu/libc.so.6+00225322 abort+00000362
[  2] 0x00007f4c0e7baac1 /home/aditya/thundersvm/build/lib/libthundersvm.so+00277185 _ZN2el4base6Writer15triggerDispatchEv+00001265
[  3] 0x00007f4c0e7ba571 /home/aditya/thundersvm/build/lib/libthundersvm.so+00275825 _ZN2el4base6Writer15processDispatchEv+00000641
[  4] 0x00007f4c0e7c44a2 /home/aditya/thundersvm/build/lib/libthundersvm.so+00316578
[  5] 0x00007f4ff7f75ab3 /home/aditya/Matlab/bin/glnxa64/../../sys/os/glnxa64/libiomp5.so+00658099 __kmp_invoke_microtask+00000147
[  6] 0x00007f4ff7f4a9d7 /home/aditya/Matlab/bin/glnxa64/../../sys/os/glnxa64/libiomp5.so+00481751
[  7] 0x00007f4ff7f4a0da /home/aditya/Matlab/bin/glnxa64/../../sys/os/glnxa64/libiomp5.so+00479450
[  8] 0x00007f4ff7f75dad /home/aditya/Matlab/bin/glnxa64/../../sys/os/glnxa64/libiomp5.so+00658861
[  9] 0x00007f500da9c6ba              /lib/x86_64-linux-gnu/libpthread.so.0+00030394
[ 10] 0x00007f500d7d241d                    /lib/x86_64-linux-gnu/libc.so.6+01078301 clone+00000109
[ 11] 0x0000000000000000                                   <unknown-module>+00000000

Randomly, I observe that sometimes model file gets corrupted and I see 2 float values before the support vector instead of one
**example:** 
SV 
0.001 0.001 1:0.0069778599 2:0.0189685 3:0.035114001 4:0.0102248

Please let me know if you have seen these issues before.
Thanks for your time.

Regards,
Aditya

**Comment by zeyiwen** [comment]
Thanks for your feedback! We haven't seen these issues before. Would you please share the training data set, the hyper-parameters, etc., such that we can reproduce the problem and fix it.

**Comment by aditya-jonnalagadda** [comment]
Both the issues happen randomly, but I think I am able to reproduce the first issue consistently with the attached training data and the command,
svm_train_matlab({'-c', num2str(0.01), '-t', num2str(0), 'feat.train', 'model'});


[feat.train.zip](https://github.com/zeyiwen/thundersvm/files/1976377/feat.train.zip)

**Comment by GODqinbin** [comment]
@aditya-jonnalagadda We found a bug on dataset loading and fixed it. You can update the codes and try again. If the issue still happens, please let us know. Thanks!

**Comment by aditya-jonnalagadda** [comment]
Hi,  It fixes the original issue, but breaks something else. Matlab crashes but nothing is present in the dump file. Attached the new feature file and below is the cross validation command used (I think it crashes for any c value, tried 2-3 values)

svm_train_matlab({'-v', '5', '-c', num2str(0.01), '-t', num2str(0), 'feat.train'});

feature file is too big to upload here, here is the google drive [link](https://drive.google.com/file/d/1q2Tx0YsJLCgTA3ya3anGtlX3gJCQsc2D/view?usp=sharing)

**Comment by GODqinbin** [comment]
@aditya-jonnalagadda  Sorry, we did not handle the boundary well when reading the dataset. We just fixed it. Now both datasets can work on our machines. You can try again. If the issue still happens, please let us know. Thanks!
