### ISSUE TITLE
Matlab, Error using calllib Library was not found

### ISSUE THREAD

**Issue by mykilla** [zeyiwen/thundersvm#64]
After building, failed to test Matlab examples in Matlab R2017a. The error is "Matlab, Error using calllib Library was not found" for line 15 "calllib('libthundersvm', 'thundersvm_train', length(str2), str2)" in file "svm_train_matlab.m" of \Matlab subdirectory.

**Comment by GODqinbin** [comment]
Thanks for your feedback. There are some bugs with Matlab on Windows. We just fixed it. You can update the codes and try again.

**Comment by mykilla** [comment]
Issue solved, thanks.
