### ISSUE TITLE
thundersvmScikit Windows: Debug Assertion Failed

### ISSUE THREAD

**Issue by mattm401** [zeyiwen/thundersvm#68]
I have a large(ish) dataset I'd like to run through ThunderSVM with 100k samples at the max described by 4096 features. I converted some of my training and evaluation data over to the format for LIBSVM, but I get an error when running my data through the example code.

```
from thundersvmScikit import *
from sklearn.datasets import *

x,y = load_svmlight_file("../dataset/train.txt")
clf = SVC(verbose=True, gamma=0.5, cost=100)
clf.fit(x,y)

x2,y2=load_svmlight_file("../dataset/test.txt")
y_predict=clf.predict(x2)
score=clf.score(x2,y2)

print "test score is ", score
```
  The output I am seeing is:

> 2018-05-13 19:44:21,657 INFO [default] #instances = 10208, #features = 4096
> 2018-05-13 19:44:23,824 INFO [default] #classes = 2
> 2018-05-13 19:45:48,808 INFO [default] working set size = 1024
> 2018-05-13 19:45:48,816 INFO [default] training start
> 2018-05-13 19:45:49,366 INFO [default] global iter = 0, total local iter = 512, diff = 2
> 2018-05-13 19:46:01,138 INFO [default] global iter = 93, total local iter = 33607, diff = 0.000996124
> 2018-05-13 19:46:01,144 INFO [default] rho = -0.305637
> 2018-05-13 19:46:01,146 INFO [default] #sv = 10179
> 2018-05-13 19:46:05,729 INFO [default] #total unique sv = 10179
> 2018-05-13 19:46:05,840 INFO [default] training finished
> 2018-05-13 19:47:10,357 INFO [default] #instances = 2904, #features = 4096

 Then I seem to get this error:

![image](https://user-images.githubusercontent.com/1121334/39972970-0502f404-56e7-11e8-923f-ca136bf3c6c2.png)

Oddly I seem to be able to run the default code and data through so I am note sure why everything seems to break when I run my data through it.

**Comment by GODqinbin** [comment]
It seems the program crash in svm predict. Would you please share the training and test data set?  So we can reproduce the problem and fix it.

**Comment by mattm401** [comment]
Hi, you can download the test data here:
http://www.cs.umd.edu/~mattm/docs/test_data.zip

I'd definitely appreciate the help figuring out what the issue is, I love fact that you have an Scikit interface!

**Comment by GODqinbin** [comment]
We found there was a bad memory access in svm predict. We have fixed it. The subset of the datasets can work on my windows now. You can update the codes and try again. If the problem still exists, please let us know. Thanks!
