### ISSUE TITLE
Option to disable prediction of train examples after training

### ISSUE THREAD

**Issue by julianofoleiss** [zeyiwen/thundersvm#72]
Other than sanity testing the training procedure there is no reason to predict the entire training sample after training. It may take a long time and serves no real purpose (in most machine learning applications).

I'd like to suggest a command line option that disables predicting the training samples after training is done. The default may even be "on" to avoid breaking scripts that need to parse that information.

Thanks!

**Comment by zeyiwen** [comment]
Thank you for the feedback! We have disabled the error prediction on the training set after training.

To avoid having too many command line options, we haven't added a command line option for this. Users who want to obtain training error can simply run ```thundersvm-predict``` :)

**Comment by julianofoleiss** [comment]
Thank you very much! I believe this will be useful for everyone :)
