### ISSUE TITLE
Installing ThunderSVM as a system-wide library

### ISSUE THREAD

**Issue by varneyo** [zeyiwen/thundersvm#73]
Hi I am fairly new to using python and I am struggling to include the build in my anaconda python environment. With other builds having the similar process of using CMake then visual studios I have then run a setup.py which I believe links, somehow anaconda and the build so that it can be used in all of my project without having to be in the folder that it was built in. 

I am on windows, and so far I have built and run the sk_test.py example from within the the default thundersvm fold that github placed on my C\users\<username>\thundersvm.

Apologies if I have missed something but is there a way that I could link thundersvm to my anaconda environment?

**Comment by zeyiwen** [comment]
It sounds like ThunderSVM needs to be installed as a system library in Windows to allow access from "everywhere". ThunderSVM doesn't support this currently. We will consider this in our future upgrade, if many users have such requirements.

**Comment by zeyiwen** [comment]
ThunderSVM supports this functionality now. Please have a try. Thanks for our contributors!
