### ISSUE TITLE
RBF kernel always used for prediction

### ISSUE THREAD

**Issue by kiramt** [zeyiwen/thundersvm#74]
When loading a model file and using it to make predictions, the RBF kernel is always used, regardless of what is set in the model file. Looks like the problem is here:

(svmmodel.cpp)
```
} else if (feature == "kernel_type") {
            string value;
            ifs >> value;
            for (int i = 0; i < 6; i++) {
                if (feature == SvmParam::kernel_type_name[i])   <-----------line 219: 'feature' should be 'value' 
param.kernel_type = static_cast<SvmParam::KERNEL_TYPE>(i);
```

**Comment by GODqinbin** [comment]
Thanks. We are appreciated that you found the bug and located it. We have fixed it now.
