### ISSUE TITLE
cann't use grid.py

### ISSUE THREAD

**Issue by yulong314** [zeyiwen/thundersvm#75]
as mentioned in faq:"So the script grid.py in LIBSVM can be used for ThunderSVM with minor modifications",  but there is always an error of "RuntimeError: get no rate"  when using grid.py with thundersvm.
I found that  these is no  "Cross Validation Accuracy" printed out by thundersvm-train.exe as by libsvm's svm-train.exe  which is needed by grid.py to know the "rate".

**Comment by zeyiwen** [comment]
Thanks for the feedback! We've updated the code, and fixed the problem. Please pull the new version, and recompile thundersvm.

**Comment by yulong314** [comment]
It would  be better to change "Accuracy" to "Cross Accuracy"  as grid.py search  'Cross' from output message.   Otherwise we may need to change the grid.py 's "find('Cross') " into find('Accuracy'),

**Comment by zeyiwen** [comment]
Thanks! The "Accuracy" has been changed to "Cross Accuracy". Please try the updated code.
