### ISSUE TITLE
Convergence issue

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [zeyiwen/thundersvm#77]
Hi,

I am training SVM with a linear kernel. Sometimes the model doesn't converge and continues for many hours. Is it possible to prevent this? (Maybe by somehow modifying the STOP condition, not sure)

Thanks

**Comment by zeyiwen** [comment]
Could you please share the data set and the hyper-parameters that you used? If we can reproduce the problem, we should be able to fix it.

**Comment by aditya-jonnalagadda** [comment]
The command I am using is svm_train_matlab({'-c', num2str(0.01), '-t', num2str(0), 'feat.train', 'model'});
And the feaat.train file is attached as a zip folder.
[Convergence_issue.zip](https://github.com/zeyiwen/thundersvm/files/2120801/Convergence_issue.zip)


Thanks for your time.

**Comment by zeyiwen** [comment]
We've fixed the convergence issue. Please try the latest version of ThunderSVM.

**Comment by aditya-jonnalagadda** [comment]
The issue had been fixed in the latest code. Thanks.
