### ISSUE TITLE
Matlab crash 

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [zeyiwen/thundersvm#78]
Hi, Matlab crashed while training the SVM using the command svm_train_matlab({'-c', num2str(0.01), '-t', num2str(0), 'feat.train', 'model'}); 

Matlab stack doesn't have thundersvm call in it, but it seems to have crashed during the training of SVM.
Crash files are located at [https://drive.google.com/file/d/1wjVTWRtxuiXyTOi_sxyZ8nBq82yuHtm2/view?usp=sharing](url) Please take a look if you have time.

Please feel free to close it if it is not related to thundersvm.

Thanks,
Aditya

**Comment by aditya-jonnalagadda** [comment]
Please close it if it is not due to thundersvm.

Thanks for your time.

**Comment by GODqinbin** [comment]
I've tested your dataset and I can run the command on Matlab successfully. I can't find useful information in your log file. It seems Matlab didn't call thundersvm. Maybe you can reinstall Matlab or try other interfaces. Thanks.

**Comment by aditya-jonnalagadda** [comment]
Probably a memory issue on my side, Thank you
