### ISSUE TITLE
Scikitlearn wrapper kernel parameters

### ISSUE THREAD

**Issue by ikiskin** [zeyiwen/thundersvm#85]
New users may be confused about kernel selection, due to the syntax difference with libsvm's scikitlearn:
`SVC(kernel='rbf')`
and thundersvm's:
`SVC(kernel=2)`
Running thundersvm with `kernel='rbf'` does not return an error, and the optimization fails (objective -inf). I would suggest either updating the interface to match libsvm's scikitlearn syntax and/or alerting the user when an invalid kernel (and possibly others) argument is passed.

**Comment by GODqinbin** [comment]
Thanks for your feedback. We have improved the interface and the usage of kernel parameter is the same with libsvm now.

**Comment by ikiskin** [comment]
Great, just a few spots left in the documentation to fix, under the Usage heading on [https://github.com/zeyiwen/thundersvm/tree/master/python](https://github.com/zeyiwen/thundersvm/tree/master/python) subheadings: "SVM classification", "One-class SVMs", and "SVM regression".
`class SVC(kernel = 'rbf', ...` etc

**Comment by GODqinbin** [comment]
Thank you very much. The doc has been fixed.
