### ISSUE TITLE
kernel = KERNEL_TYPE.index(self.kernel)

### ISSUE THREAD

**Issue by pardedetalenta** [zeyiwen/thundersvm#86]
Please help, whats wrong with kernel?  

File "/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 96, in fit
kernel = KERNEL_TYPE.index(self.kernel)
ValueError: 2 is not in list

this is my code 

# -*- coding: utf-8 -*-
"""
Created on Thu Jun 21 08:18:36 2018

@author: Talenta
"""

import pandas as pd
import numpy as np
dataset = pd.read_csv('/my_data/smote_pca_data.csv')

data_test = pd.read_csv('/my_data/test_training_pca.csv')

y_train = dataset.iloc[:,3]

X_train = dataset.iloc[:,1:3]

y_test = data_test.iloc[:,3]

X_test = data_test.iloc[:,1:3]

from thundersvmScikit import *

x = np.asarray(X_train)

y = np.asarray(y_train)

x_train = x.tolist()
y_train = y.tolist()

xt = np.asarray(X_test)

yt = np.asarray(y_test)

xtest = xt.tolist()
ytest = yt.tolist()

clf = SVC(verbose = True, C= 0.1, gamma = 0.01)

print("God loves you!")

clf.fit(x_train,y_train)

clf.score(xtest, ytest)

clf.save_to_file('./')

**Comment by GODqinbin** [comment]
Thanks for your feedback. We've fixed the bug. We change the kernel parameters to be the same with libsvm scikit interface. You can try again.

**Comment by pardedetalenta** [comment]
thank you @GODqinbin 

can i ask you again? or i have to make new issue? it's about Fatal log at [/floyd/home/thundersvm/src/thundersvm/model/svmmodel.cpp:135] its because i want to save the model with -> clf.save_to_file('/output/')

**Comment by GODqinbin** [comment]
It means the model file didn't create successfully. You should specify the model file name. For example: clf.save_to_file('./model'). We'll update the docs to give the example of save_to_file().

**Comment by pardedetalenta** [comment]
Thank you so much @GODqinbin 👍
