### ISSUE TITLE
Convergence issue

### ISSUE THREAD

**Issue by aditya-jonnalagadda** [zeyiwen/thundersvm#88]
Hi,

Training of the SVM is not converging for the attached file. If you have time, Please look into it.

Tested with Code base : Github 4th July
Command used : svm_train_matlab({'-c', num2str(0.01), '-t', num2str(0), 'feat.train', 'model'});
features file: https://drive.google.com/open?id=1phq-VsmmJ8x9UbYw17fGxU0pRPB_ezie

Thanks for your time.

**Comment by zeyiwen** [comment]
I've tested thundersvm with the hyper-parameters, and thundersvm worked fine in my machine. The training took about 2 minutes on the CPUs in my workstation. Perhaps, you need to wait a bit longer?

**Comment by aditya-jonnalagadda** [comment]
I will test it again, thanks.
