### ISSUE TITLE
class_weight = 'balanced' / "balanced" / {1:116}

### ISSUE THREAD

**Issue by pardedetalenta** [zeyiwen/thundersvm#91]
I'm trying to class_weight with this code: 

clf = SVC(verbose = True, C=0.1, gamma = 0.01, class_weight ="balanced") or 'balanced' or {1:116} but it give this error : 

clf.fit(x_train,y_train)
File "/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 103, in fit
fit(X, y, solver_type, kernel)
/usr/local/lib/python3.6/site-packages/thundersvm-github_master-py3.6.egg/thundersvmScikit.py", line 159, in _dense_fit
weight_label[:] = self.class_weight.keys()
AttributeError: 'str' object has no attribute 'keys'

**Comment by GODqinbin** [comment]
I'm sorry that ThunderSVM doesn't support 'balanced' yet and I've corrected the document. You can use dict format for example `clf = SVC(class_weight={1:116})`. There should be no double quote in your dict value. Thanks.

**Comment by pardedetalenta** [comment]
Hi @GODqinbin, thank you but class_weight={1:116} give me this error: 
weight_label[:] = self.class_weight.keys()
TypeError: 'dict_keys' object does not support indexing

**Comment by GODqinbin** [comment]
Thanks for your feedback. The bug is happened when using python3. We have fixed the bug. You can try again.

**Comment by pardedetalenta** [comment]
Thank you @GODqinbin 👍
