### ISSUE TITLE
Problems with MATLAB interface

### ISSUE THREAD

**Issue by rsadek** [zeyiwen/thundersvm#94]
Hello ThunderSVM team!
I'm unable to run ThunderSVM through the MATLAB interface on Ubuntu 16.04 Linux. After following the installation instructions, I get 

Error using loadlibrary
Could not find file ../include/thundersvm/svm_interface_api.h.

Error in loadlibrary

Error in svm_train_matlab (line 16)
            loadlibrary('../build/lib/libthundersvm.so', '../include/thundersvm/svm_interface_api.h')

I tried creating build and include directories above my working directory and moving the header and shared library into them. This partially worked. It was able to find the .h and the .so. However, it fails with errors like 

Error using loadlibrary
There was an error loading the library "/home/sadekrs1/work/virga/training/../build/lib/libthundersvm.so"

Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcmm' required by
'/home/sadekrs1/work/virga/build/lib/libthundersvm.so'
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm' required by
'/home/sadekrs1/work/virga/build/lib/libthundersvm.so'
Missing symbol '_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm' required by
'/home/sadekrs1/work/virga/build/lib/libthundersvm.so'

Please, do you have any suggestions on what might be wrong and/or how to fix it?
Thanks!
Ramy

**Comment by GODqinbin** [comment]
Your error "/home/sadekrs1/work/virga/training/../build/lib/libthundersvm.so" showed that you didn't run your codes in thundersvm/Matlab directory. You should cd into thundersvm/Matlab directory first.

**Comment by rsadek** [comment]
Thank you for your prompt response! Unfortunately when I run from the thundersvm/Matlab directory, I get the stdlibc++ errors listed above. Any suggestions on how to fix this problem?
