### ISSUE TITLE
std::bad alloc core dump saved model

### ISSUE THREAD

**Issue by pardedetalenta** [zeyiwen/thundersvm#97]
Hi, I want to ask about the model I've been saved. When I want to predict my data, it gives me error bad alloc core dump. My code is like on documentation here:

clf = SVC()

clf.load_from_file('name.model')

y_pred = clf.predict(X)

**Comment by GODqinbin** [comment]
Can you share your dataset? Then we can reproduce the problem and debug it. Thanks.

**Comment by pardedetalenta** [comment]
I train my model with this dataset https://www.floydhub.com/talenta10/datasets/my-cool-dataset/1 -> smote_pca_data.csv and I test with this dataset https://www.floydhub.com/talenta10/datasets/my-cool-dataset/8 -> dataset_80.csv

Kindly check it, because when I save my model with this dataset https://www.floydhub.com/talenta10/datasets/my-cool-dataset/1 -> pca_dataset.csv and test it with the same dataset_80.csv it works fine

Thank you

**Comment by pardedetalenta** [comment]
I've updated my library and train again, but it still gives me the same error?

**Comment by zeyiwen** [comment]
We can't reproduce this issue... Have you specified the ```max_mem_size``` inside ```SVC(...)```?

We notice that if the GPU memory is smaller than 8GB, the ```bad alloc``` issue may occur.
