### ISSUE TITLE
The svm.svm_predict result is different with the OneClassSVM.predict

### ISSUE THREAD

**Issue by baibaiw5** [zeyiwen/thundersvm#98]
After a  one class svm model is trained,  I test the predict function between svm.svm_predict  and OneClassSVM.predict , I found that the predict results is different.
My model and test data file is :https://pan.baidu.com/s/1NCIk65yAY8gdndCa1T-BZw
#----------------------
The svm.svm_predict result is the same with the result predict by bin/thundersvm-predict .
label -1:18
label  1:82
--The svm.svm_predict test code:
feat_file="mini.libsvm"
model_file="user.model"
predict_file='user.predict2'
y,x=svm_read_problem(feat_file)
svm_predict(y,x,model_file,predict_file)
#----------------------
The predict result:
label -1:25
label  1:75
--The OneClassSVM.predict test code:
clf=OneClassSVM()
clf.load_from_file(model_file)
X, y = load_svmlight_file(feat_file, zero_based=False, multilabel=False)
preds=ocs.predict(X)

**Comment by GODqinbin** [comment]
Thanks for your feedback. We found that the load_svmlight_file function will generate zero-based format data. The zero_based parameter is the description of input file but not the output data, which is out of our expectation. We have fixed the bug. The results are the same now. You can update the codes and use the same instructions to try again. Thanks.
