### ISSUE TITLE
Possible data race issue in kernel function c_smo_solve_kernel 

### ISSUE THREAD

**Issue by DayDayStudyNightNightUp** [zeyiwen/thundersvm#99]
Hello there!

Currently I am learning thundersvm source code, and might find a data race issue in kernel function c_smo_solve_kernel located in src/thundersvm/kernel/smo_kernel.cu.

Say we have setup grid size to 1, block size to 34, and ws_size = 8, Cp = 1.0, Cn = 1.0, row_len = 2, eps = 1.0, max_t_iter = 3.

Here is how float_type define in :
```
typedef double float_type;
```

Here is how f_idx2reduce and f_val2reduce computed:
```
        int *f_idx2reduce = shared_mem; //temporary memory for reduction
        float_type *f_val2reduce = (float_type *) &shared_mem[ws_size]; //f values used for reduction.
```

Here is get_block_min's action before reach first barrier:
```
    __device__ int get_block_min(const T *values, int *index) {
        int tid = threadIdx.x;
        index[tid] = tid;
        __syncthreads();
       ........
   }
```

Here is suspicious data race code from line 56 to 60 in kernel function c_smo_solve_kernel:
```
            if (is_I_up(a, y, Cp, Cn))
                f_val2reduce[tid] = f;
            else
                f_val2reduce[tid] = INFINITY;
            int i = get_block_min(f_val2reduce, f_idx2reduce);
```

Then for thread (32 0 0), its f_idx2reduce[32] refers to shared_mem[32], and it will write data 32 to shared_mem[32]; 
At the same time, for thread (12 0 0), its f_val2reduce[12] (double *ptr 8 Byte, int *ptr 4 Byte) refers to shared_mem[12 * 2 + 8], and it will write data f or INFINITY to shared_mem[32];
Because (32 0 0) and (12 0 0) aren't in the same thread warp, CUDA can not guarantee the writing order to shared_mem[32], isn't here will have write & write data race?

Thanks for the help! :)

**Comment by DayDayStudyNightNightUp** [comment]
@zeyiwen 
Thanks for the reply!

Yes I have noted ws_size existed and set it to 8 while having 34 threads in block. In such setup, isn't there a write & write data race?


For nu_smo_solve_kernel function in same file, line 150:
```
            if (y > 0 && a < C)
                f_val2reduce[tid] = f;
            else
                f_val2reduce[tid] = INFINITY;
            __syncthreads();
            int ip = get_block_min(f_val2reduce, f_idx2reduce);
```
Seems these two functions set f_val2reduce and f_idx2reduce in the same way, I guess ws_size should be checked in order to avoid such issue?

**Comment by zeyiwen** [comment]
There is no race condition in the code... The key reason is that ```ws_size``` is always larger or equal to block size. Therefore, the setting you described doesn't occur in our program.

**Comment by DayDayStudyNightNightUp** [comment]
Thanks for more detail! But what confuse me is if ws_size is always larger or equal to block size, why should add a barrier in kernel function nu_smo_solve_kernel located in cu-kernels.cu at line 150? 
```
            if (y > 0 && a < C)
                f_val2reduce[tid] = f;
            else
                f_val2reduce[tid] = INFINITY;
            __syncthreads(); // here is the barrier function
            int ip = get_block_min(f_val2reduce, f_idx2reduce);
```

**Comment by zeyiwen** [comment]
This is the requirement of the reduction operation. Please read [this](https://developer.download.nvidia.com/compute/cuda/1.1-Beta/x86_website/projects/reduction/doc/reduction.pdf) for more information.
